# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hb_hw_interface/position_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class position_cmd(genpy.Message):
  _md5sum = "3c27cff7b342ce46d7f949fb78b6703f"
  _type = "hb_hw_interface/position_cmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[11] angle_cmd #cmd to arduino functions that move the arm.
float32[11] velocity_cmd ##cmd to arduino functions that move wheels."""
  __slots__ = ['angle_cmd','velocity_cmd']
  _slot_types = ['float32[11]','float32[11]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       angle_cmd,velocity_cmd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(position_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.angle_cmd is None:
        self.angle_cmd = [0.] * 11
      if self.velocity_cmd is None:
        self.velocity_cmd = [0.] * 11
    else:
      self.angle_cmd = [0.] * 11
      self.velocity_cmd = [0.] * 11

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_11f().pack(*self.angle_cmd))
      buff.write(_get_struct_11f().pack(*self.velocity_cmd))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 44
      self.angle_cmd = _get_struct_11f().unpack(str[start:end])
      start = end
      end += 44
      self.velocity_cmd = _get_struct_11f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.angle_cmd.tostring())
      buff.write(self.velocity_cmd.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 44
      self.angle_cmd = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=11)
      start = end
      end += 44
      self.velocity_cmd = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=11)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11f = None
def _get_struct_11f():
    global _struct_11f
    if _struct_11f is None:
        _struct_11f = struct.Struct("<11f")
    return _struct_11f
