position_trajectory_controller:
  name: ""
  type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
  joints:
    - Shoulder_Fi
    - Shoulder_Theta_Joint
    - Elbow_Fi
    - Elbow_Theta
    - Wrist_Fi
    - Wrist_Theta

gripper_controller:
  name: ""
  type: position_controllers/JointTrajectoryController
  joints:
   - GCore_RSL

mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : ['Base_WheelLF', 'Base_WheelLB']
  right_wheel : ['Base_WheelRF', 'Base_WheelRB']
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  wheel_separation : 0.5
  wheel_radius : 0.3